//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitchARideService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HitchARideEntities : DbContext
    {
        public HitchARideEntities()
            : base("name=HitchARideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<vw_Full_User_Information> vw_Full_User_Information { get; set; }
    }
}
